# Generated by Django 4.2.6 on 2023-12-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0002_categories_shoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoes',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='shoes',
            name='sname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
