# Generated by Django 4.2.6 on 2023-12-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0003_shoes_price_shoes_sname'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='cdesc',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
